### ISSUE TITLE
Interface name is mutable

### ISSUE THREAD

**Issue by dushyant88** [deliveryhero/lymph#47]
The interface name is used to identify the interface when it is installed in a container. There is a method in the container that allows you to install interfaces.
```python
def install_interface(self, cls, interface_name=None): 
```
The ```interface_name``` is associated to the interface and that is what is used to identify the interface too, including discovery.

Now when you have an interface, you can change the ```name``` of the interface if you have access to the interface instance and that will not update the container.

Eg.
```python
echo_interface = container.installed_interfaces['echo']
echo_interface.name = 'something-else'
```

This would not break the request call to the the interface, but it indicates that if you change the name the of the interface you would be able to discover it with the new name runtime.

To follow the discussion and possibly a solution checkout this discussion on the PR[https://github.com/deliveryhero/lymph/pull/37#discussion-diff-20519884]

**Comment by emulbreh** [comment]
not really a problem, we don't usually enforce immutability in Python
